admin_employment:
    resource: "@AdminBundle/Controller/EmploymentController.php"
    type:     annotation

admin_doctor:
    resource: "@AdminBundle/Controller/DoctorController.php"
    type:     annotation

admin_nurse:
    resource: "@AdminBundle/Controller/NurseController.php"
    type:     annotation

admin_employee:
    resource: "@AdminBundle/Controller/EmployeeController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"