admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"